# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52e24a48cd28afdf9d2e3d6a3d267b7dd6626674f1c4100d274e05edf533faed61f77bd3ea8968ff0e965cf0ae0c58f836effcfee2cd055bb9acaad6f92df221

test:
  secret_key_base: c818d35f19b4dff89229244319e1e47580147de667734c5bff421877480a6145991f30f456966a4c831f67283908a537a286af2eea81004c11a67f591bb49656

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
